"""
SQLAlchemy 2.0 declarative Base class.

All ORM models inherit from Base, which provides:
  - id          — UUID primary key with server-side gen_random_uuid()
  - created_at  — UTC timestamp set on INSERT
  - updated_at  — UTC timestamp set on INSERT and refreshed on every UPDATE
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Shared declarative base for all ORM models.

    Every table that inherits from Base automatically receives:
      - id         (UUID, primary key, server default: gen_random_uuid())
      - created_at (timestamptz, server default: now(), non-null)
      - updated_at (timestamptz, server default: now(), auto-updated on change, non-null)
    """

    # Primary key — UUID generated by PostgreSQL so the DB is the source of truth.
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # Audit timestamps — both stored as UTC (timezone=True).
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
