"""Add remaining fintech tables

Revision ID: 1226ffb6fd73
Revises: 0010
Create Date: 2026-06-12 14:00:54.069417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1226ffb6fd73'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_api_keys',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_developer_api_keys_tenant_id'), 'developer_api_keys', ['tenant_id'], unique=False, schema='public')
    op.create_table('employees',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('kyc_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('bank_details', sa.String(length=500), nullable=True),
    sa.Column('education', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_docs', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_employees_email'), 'employees', ['email'], unique=False, schema='public')
    op.create_index(op.f('ix_public_employees_kyc_status'), 'employees', ['kyc_status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_employees_status'), 'employees', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_employees_tenant_id'), 'employees', ['tenant_id'], unique=False, schema='public')
    op.create_table('headcount_plans',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('budget_allocated', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_headcount_plans_tenant_id'), 'headcount_plans', ['tenant_id'], unique=False, schema='public')
    op.create_table('integration_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_integration_configs_tenant_id'), 'integration_configs', ['tenant_id'], unique=False, schema='public')
    op.create_table('webhook_subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('event_types', sa.String(length=500), nullable=False),
    sa.Column('secret_token', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_webhook_subscriptions_tenant_id'), 'webhook_subscriptions', ['tenant_id'], unique=False, schema='public')
    op.create_table('attendance_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_status', sa.String(length=50), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_attendance_logs_employee_id'), 'attendance_logs', ['employee_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_attendance_logs_tenant_id'), 'attendance_logs', ['tenant_id'], unique=False, schema='public')
    op.create_table('attrition_predictions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_drivers', sa.String(length=500), nullable=True),
    sa.Column('recommendations', sa.String(length=1000), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_attrition_predictions_employee_id'), 'attrition_predictions', ['employee_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_attrition_predictions_tenant_id'), 'attrition_predictions', ['tenant_id'], unique=False, schema='public')
    op.create_table('leave_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_leave_requests_tenant_id'), 'leave_requests', ['tenant_id'], unique=False, schema='public')
    op.create_table('payroll_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('pay_period', sa.String(length=50), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('allowances', sa.Float(), nullable=False),
    sa.Column('deductions_tds', sa.Float(), nullable=False),
    sa.Column('deductions_pf', sa.Float(), nullable=False),
    sa.Column('deductions_esi', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_payroll_logs_employee_id'), 'payroll_logs', ['employee_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_payroll_logs_pay_period'), 'payroll_logs', ['pay_period'], unique=False, schema='public')
    op.create_index(op.f('ix_public_payroll_logs_tenant_id'), 'payroll_logs', ['tenant_id'], unique=False, schema='public')
    op.create_table('performance_reviews',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('goals_met_pct', sa.Float(), nullable=False),
    sa.Column('feedback', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_performance_reviews_employee_id'), 'performance_reviews', ['employee_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_performance_reviews_tenant_id'), 'performance_reviews', ['tenant_id'], unique=False, schema='public')
    op.create_table('salary_structures',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('monthly_base_salary', sa.Float(), nullable=False),
    sa.Column('allowances', sa.Float(), nullable=False),
    sa.Column('pf_opt_in', sa.Boolean(), nullable=False),
    sa.Column('esi_opt_in', sa.Boolean(), nullable=False),
    sa.Column('pan_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_salary_structures_employee_id'), 'salary_structures', ['employee_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_salary_structures_tenant_id'), 'salary_structures', ['tenant_id'], unique=False, schema='public')
    op.create_table('shift_schedules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('day_of_week', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_shift_schedules_employee_id'), 'shift_schedules', ['employee_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_shift_schedules_tenant_id'), 'shift_schedules', ['tenant_id'], unique=False, schema='public')
    op.create_table('webhook_delivery_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.String(length=2000), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.String(length=2000), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['public.webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_webhook_delivery_logs_subscription_id'), 'webhook_delivery_logs', ['subscription_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_webhook_delivery_logs_tenant_id'), 'webhook_delivery_logs', ['tenant_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_webhook_delivery_logs_tenant_id'), table_name='webhook_delivery_logs', schema='public')
    op.drop_index(op.f('ix_public_webhook_delivery_logs_subscription_id'), table_name='webhook_delivery_logs', schema='public')
    op.drop_table('webhook_delivery_logs', schema='public')
    op.drop_index(op.f('ix_public_shift_schedules_tenant_id'), table_name='shift_schedules', schema='public')
    op.drop_index(op.f('ix_public_shift_schedules_employee_id'), table_name='shift_schedules', schema='public')
    op.drop_table('shift_schedules', schema='public')
    op.drop_index(op.f('ix_public_salary_structures_tenant_id'), table_name='salary_structures', schema='public')
    op.drop_index(op.f('ix_public_salary_structures_employee_id'), table_name='salary_structures', schema='public')
    op.drop_table('salary_structures', schema='public')
    op.drop_index(op.f('ix_public_performance_reviews_tenant_id'), table_name='performance_reviews', schema='public')
    op.drop_index(op.f('ix_public_performance_reviews_employee_id'), table_name='performance_reviews', schema='public')
    op.drop_table('performance_reviews', schema='public')
    op.drop_index(op.f('ix_public_payroll_logs_tenant_id'), table_name='payroll_logs', schema='public')
    op.drop_index(op.f('ix_public_payroll_logs_pay_period'), table_name='payroll_logs', schema='public')
    op.drop_index(op.f('ix_public_payroll_logs_employee_id'), table_name='payroll_logs', schema='public')
    op.drop_table('payroll_logs', schema='public')
    op.drop_index(op.f('ix_public_leave_requests_tenant_id'), table_name='leave_requests', schema='public')
    op.drop_index(op.f('ix_public_leave_requests_employee_id'), table_name='leave_requests', schema='public')
    op.drop_table('leave_requests', schema='public')
    op.drop_index(op.f('ix_public_attrition_predictions_tenant_id'), table_name='attrition_predictions', schema='public')
    op.drop_index(op.f('ix_public_attrition_predictions_employee_id'), table_name='attrition_predictions', schema='public')
    op.drop_table('attrition_predictions', schema='public')
    op.drop_index(op.f('ix_public_attendance_logs_tenant_id'), table_name='attendance_logs', schema='public')
    op.drop_index(op.f('ix_public_attendance_logs_employee_id'), table_name='attendance_logs', schema='public')
    op.drop_table('attendance_logs', schema='public')
    op.drop_index(op.f('ix_public_webhook_subscriptions_tenant_id'), table_name='webhook_subscriptions', schema='public')
    op.drop_table('webhook_subscriptions', schema='public')
    op.drop_index(op.f('ix_public_integration_configs_tenant_id'), table_name='integration_configs', schema='public')
    op.drop_table('integration_configs', schema='public')
    op.drop_index(op.f('ix_public_headcount_plans_tenant_id'), table_name='headcount_plans', schema='public')
    op.drop_table('headcount_plans', schema='public')
    op.drop_index(op.f('ix_public_employees_tenant_id'), table_name='employees', schema='public')
    op.drop_index(op.f('ix_public_employees_status'), table_name='employees', schema='public')
    op.drop_index(op.f('ix_public_employees_kyc_status'), table_name='employees', schema='public')
    op.drop_index(op.f('ix_public_employees_email'), table_name='employees', schema='public')
    op.drop_table('employees', schema='public')
    op.drop_index(op.f('ix_public_developer_api_keys_tenant_id'), table_name='developer_api_keys', schema='public')
    op.drop_table('developer_api_keys', schema='public')
    # ### end Alembic commands ###
